cmake_minimum_required(VERSION 3.16)
get_filename_component(name ${CMAKE_CURRENT_SOURCE_DIR} NAME)
project(${name})

file(GLOB src src/*.c src/*/*.c)

make_directory(${CMAKE_CURRENT_SOURCE_DIR}/src/parsers)
ragel(${name} src/parsers/tsip_parser_uri.c ./ragel/tsip_parser_uri.rl)
ragel(${name} src/parsers/tsip_parser_message.c ./ragel/tsip_parser_message.rl)
ragel(${name} src/parsers/tsip_parser_header.c ./ragel/tsip_parser_header.rl)

ragel(${name} src/headers/tsip_header_Allow.c ./ragel/tsip_parser_header_Allow.rl)
ragel(${name} src/headers/tsip_header_Allow_Events.c ./ragel/tsip_parser_header_Allow_Events.rl)
######ragel(${name} src/headers/tsip_header_Authorization.c ./ragel/tsip_parser_header_Authorization.rl)
ragel(${name} src/headers/tsip_header_Call_ID.c ./ragel/tsip_parser_header_Call_ID.rl)
ragel(${name} src/headers/tsip_header_Content_Length.c ./ragel/tsip_parser_header_Content_Length.rl)
ragel(${name} src/headers/tsip_header_Content_Type.c ./ragel/tsip_parser_header_Content_Type.rl)
ragel(${name} src/headers/tsip_header_Contact.c ./ragel/tsip_parser_header_Contact.rl)
ragel(${name} src/headers/tsip_header_CSeq.c ./ragel/tsip_parser_header_CSeq.rl)
ragel(${name} src/headers/tsip_header_Date.c ./ragel/tsip_parser_header_Date.rl)
ragel(${name} src/headers/tsip_header_Dummy.c ./ragel/tsip_parser_header_Dummy.rl)
ragel(${name} src/headers/tsip_header_Event.c ./ragel/tsip_parser_header_Event.rl)
ragel(${name} src/headers/tsip_header_Expires.c ./ragel/tsip_parser_header_Expires.rl)
ragel(${name} src/headers/tsip_header_From.c ./ragel/tsip_parser_header_From.rl)
ragel(${name} src/headers/tsip_header_Max_Forwards.c ./ragel/tsip_parser_header_Max_Forwards.rl)
ragel(${name} src/headers/tsip_header_Min_Expires.c ./ragel/tsip_parser_header_Min_Expires.rl)
ragel(${name} src/headers/tsip_header_Min_SE.c ./ragel/tsip_parser_header_Min_SE.rl)
ragel(${name} src/headers/tsip_header_Path.c ./ragel/tsip_parser_header_Path.rl)
ragel(${name} src/headers/tsip_header_P_Access_Network_Info.c ./ragel/tsip_parser_header_P_Access_Network_Info.rl)
ragel(${name} src/headers/tsip_header_P_Asserted_Identity.c ./ragel/tsip_parser_header_P_Asserted_Identity.rl)
ragel(${name} src/headers/tsip_header_P_Associated_URI.c ./ragel/tsip_parser_header_P_Associated_URI.rl)
ragel(${name} src/headers/tsip_header_P_Charging_Function_Addresses.c ./ragel/tsip_parser_header_P_Charging_Function_Addresses.rl)
ragel(${name} src/headers/tsip_header_P_Preferred_Identity.c ./ragel/tsip_parser_header_P_Preferred_Identity.rl)
ragel(${name} src/headers/tsip_header_Privacy.c ./ragel/tsip_parser_header_Privacy.rl)
########ragel(${name} src/headers/tsip_header_Proxy_Authenticate.c ./ragel/tsip_parser_header_Proxy_Authenticate.rl)
#########ragel(${name} src/headers/tsip_header_Proxy_Authorization.c ./ragel/tsip_parser_header_Proxy_Authorization.rl)
ragel(${name} src/headers/tsip_header_Proxy_Require.c ./ragel/tsip_parser_header_Proxy_Require.rl)
ragel(${name} src/headers/tsip_header_RAck.c ./ragel/tsip_parser_header_RAck.rl)
ragel(${name} src/headers/tsip_header_Record_Route.c ./ragel/tsip_parser_header_Record_Route.rl)
ragel(${name} src/headers/tsip_header_Refer_Sub.c ./ragel/tsip_parser_header_Refer_Sub.rl)
ragel(${name} src/headers/tsip_header_Refer_To.c ./ragel/tsip_parser_header_Refer_To.rl)
ragel(${name} src/headers/tsip_header_Referred_By.c ./ragel/tsip_parser_header_Referred_By.rl)
ragel(${name} src/headers/tsip_header_Require.c ./ragel/tsip_parser_header_Require.rl)
ragel(${name} src/headers/tsip_header_Route.c ./ragel/tsip_parser_header_Route.rl)
ragel(${name} src/headers/tsip_header_RSeq.c ./ragel/tsip_parser_header_RSeq.rl)
ragel(${name} src/headers/tsip_header_Server.c ./ragel/tsip_parser_header_Server.rl)
ragel(${name} src/headers/tsip_header_SIP_ETag.c ./ragel/tsip_parser_header_SIP_ETag.rl)
ragel(${name} src/headers/tsip_header_SIP_If_Match.c ./ragel/tsip_parser_header_SIP_If_Match.rl)
ragel(${name} src/headers/tsip_header_Security_Client.c ./ragel/tsip_parser_header_Security_Client.rl)
ragel(${name} src/headers/tsip_header_Security_Server.c ./ragel/tsip_parser_header_Security_Server.rl)
ragel(${name} src/headers/tsip_header_Security_Verify.c ./ragel/tsip_parser_header_Security_Verify.rl)
ragel(${name} src/headers/tsip_header_Service_Route.c ./ragel/tsip_parser_header_Service_Route.rl)
ragel(${name} src/headers/tsip_header_Session_Expires.c ./ragel/tsip_parser_header_Session_Expires.rl)
ragel(${name} src/headers/tsip_header_Subscription_State.c ./ragel/tsip_parser_header_Subscription_State.rl)
ragel(${name} src/headers/tsip_header_Supported.c ./ragel/tsip_parser_header_Supported.rl)
ragel(${name} src/headers/tsip_header_To.c ./ragel/tsip_parser_header_To.rl)
ragel(${name} src/headers/tsip_header_User_Agent.c ./ragel/tsip_parser_header_User_Agent.rl)
ragel(${name} src/headers/tsip_header_Via.c ./ragel/tsip_parser_header_Via.rl)
ragel(${name} src/headers/tsip_header_Warning.c ./ragel/tsip_parser_header_Warning.rl)
#########ragel(${name} src/headers/tsip_header_WWW_Authenticate.c ./ragel/tsip_parser_header_WWW_Authenticate.rl)

add_library(${name} ${src} ${RAGEL_${name}_FILES})
target_include_directories(${name} PUBLIC include)
target_link_libraries(${name} tinyMEDIA tinyHTTP tinyIPSec tinySIGCOMP)

test()

