cmake_minimum_required(VERSION 3.16)
get_filename_component(name ${CMAKE_CURRENT_SOURCE_DIR} NAME)
project(${name})

make_directory(${CMAKE_CURRENT_SOURCE_DIR}/src/parsers)
file(GLOB src src/*.c src/*/*.c)
ragel(${name} src/parsers/tmsrp_parser_message.c ./ragel/tmsrp_parser_message.rl)
ragel(${name} src/parsers/tmsrp_parser_uri.c ./ragel/tmsrp_parser_uri.rl)
ragel(${name} src/headers/tmsrp_header_Authentication-Info.c ./ragel/tmsrp_parser_header_Authentication-Info.rl)
ragel(${name} src/headers/tmsrp_header_Byte-Range.c ./ragel/tmsrp_parser_header_Byte-Range.rl)
ragel(${name} src/headers/tmsrp_header_Content-Type.c ./ragel/tmsrp_parser_header_Content-Type.rl)
ragel(${name} src/headers/tmsrp_header_Dummy.c ./ragel/tmsrp_parser_header_Dummy.rl)
ragel(${name} src/headers/tmsrp_header_Expires.c ./ragel/tmsrp_parser_header_Expires.rl)
ragel(${name} src/headers/tmsrp_header_Failure-Report.c ./ragel/tmsrp_parser_header_Failure-Report.rl)
ragel(${name} src/headers/tmsrp_header_From-Path.c ./ragel/tmsrp_parser_header_From-Path.rl)
ragel(${name} src/headers/tmsrp_header_Max-Expires.c ./ragel/tmsrp_parser_header_Max-Expires.rl)
ragel(${name} src/headers/tmsrp_header_Message-ID.c ./ragel/tmsrp_parser_header_Message-ID.rl)
ragel(${name} src/headers/tmsrp_header_Min-Expires.c ./ragel/tmsrp_parser_header_Min-Expires.rl)
ragel(${name} src/headers/tmsrp_header_Status.c ./ragel/tmsrp_parser_header_Status.rl)
ragel(${name} src/headers/tmsrp_header_Success-Report.c ./ragel/tmsrp_parser_header_Success-Report.rl)
ragel(${name} src/headers/tmsrp_header_To-Path.c ./ragel/tmsrp_parser_header_To-Path.rl)
ragel(${name} src/headers/tmsrp_header_Use-Path.c ./ragel/tmsrp_parser_header_Use-Path.rl)

add_library(${name} ${src} ${RAGEL_${name}_FILES})
target_include_directories(${name} PUBLIC include)
target_link_libraries(${name} tinyHTTP)

test()
