macro(test)
    file(GLOB tests test/*.c)
    foreach(test_src ${tests})
        get_filename_component(test ${test_src} NAME_WE)
        add_executable(${name}_${test} ${test_src})
        target_link_libraries(${name}_${test} ${name})
	set_target_properties(${name}_${test} PROPERTIES RUNTIME_OUTPUT_DIRECTORY test)
	add_test(${name}_${test} ./test/${name}_${test})
	#add_test(${name}_${test} "$<TARGET_FILE:${name}_${test}>")
        set_tests_properties(${name}_${test} PROPERTIES TIMEOUT 30)
    endforeach()
endmacro()
