name: CMake build

on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false

      matrix:
        os:
        - ubuntu-latest
        #- windows-latest
        #- macos-latest
        build_type:
        - Release

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: cmake -S . -B out -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build out --config ${{ matrix.build_type }}

    - name: Test
      run: ctest --verbose --test-dir out --build-config ${{ matrix.build_type }}
